require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0

  NewCops: enable

  Exclude:
    - 'db/schema.rb'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'
    - 'config/initializers/cors.rb'

Rails:
  Enabled: true

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 120
  Exclude:
    - 'db/migrate/*'

Lint/RaiseException:
  Enabled: false

Lint/StructNewOverride:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Max: 60
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Max: 10

Rails/SkipsModelValidations:
  Exclude:
    - 'lib/tasks/**/*'
    - 'db/migrate/*.rb'

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  AutoCorrect: true

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/ExponentialNotation:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true
