require: rubocop-performance

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

  TargetRubyVersion: 2.5
  TargetRailsVersion: 5.2

Rails:
  Enabled: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  IndentationWidth: 2

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent

Layout/IndentFirstHashElement:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Max: 65
  Exclude:
    - 'db/migrate/*'

Metrics/BlockLength:
  Max: 60
  Exclude:
    - 'config/routes.rb'
    - 'lib/tasks/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'db/migrate/*'

Metrics/PerceivedComplexity:
  Max: 10

Rails/CreateTableWithTimestamps:
  Exclude:
    - 'db/migrate/{2014,2015,2016,2017,2018}*.rb'

Rails/BulkChangeTable:
  Enabled: false

Rails/ReversibleMigration:
  Exclude:
    - 'db/migrate/{2014,2015,2016,2017,2018}*.rb'

Rails/SkipsModelValidations:
  Exclude:
    - 'lib/tasks/**/*'
    - 'db/migrate/*.rb'

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Style/ClassAndModuleChildren:
  AutoCorrect: true

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/IfUnlessModifier:
  Enabled: false

Style/SymbolArray:
  MinSize: 7