default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  pool: 5

development:
  <<: *default
  username: 'whatsupgenius'
  password: Rails.application.credentials.database[:password]
  database: whatsupgenius_development

test:
  <<: *default
  database: whatsupgenius_test

production:
  <<: *default
  database: whatsupgenius